### ISSUE TITLE
AcceptHeaderNegotiator

### ISSUE THREAD

**Issue by mabar** [apitte/negotiation#10]
Suffixes like `.json` are nice for debug in browser, but rest api should use Accept header.

Scenario
User sent `Accept: application/json`
Then return `ContentType: application/json` if json transformer is available and suffix was not defined in url.

**Comment by BigOHenry** [comment]
Hello, is this already implemented? In doc is `Transform response entity into response with unified format in dependence on Accept header and uri path suffix /api/v1/users(.json|.xml)`, but i cannot get it to work.

I registered XmlTransformer. Same like at docs. 
But when i add parameter to header `Accept - application/xml` or into uri `http://localhost/api-rest/v1/lookup/lookup_title.xml` it doesnt work. With header it return json. With uri it return `lookup not found` (`lookup_title` is a parameter for lookup name).

Annotations ares:

    ```
/**
     * @param ApiRequest  $request
     * @param ApiResponse $response
     * @return ApiResponse
     *
     * @Path("/{lookup}")
     * @Method("GET")
     * @RequestParameters({
     *     @RequestParameter(name="lookup", type="string", in="path", required=true, description="Name of lookup."),
     *     @RequestParameter(name="enabled-only", type="bool", in="query", required=false, description="Get only enabled values from lookup."),
     *     @RequestParameter(name="language", type="string", in="header", required=false, description="Language for description lookup values.")
     * }),
     * @Negotiations({
     * 		@Negotiation(default = true, suffix = "json"),
     * 		@Negotiation(default = false, suffix = "xml")
     * })
     */
    public function lookup(ApiRequest $request, ApiResponse $response): ApiResponse
    {
       // do some stuff
    }
```

**Comment by mabar** [comment]
Accept headers are not implemented yet, I forgot about it when I was writing the docs.

It's not clearly described in docs, I guess - by default is registered only json negotiator and there is no default implementation for xml. 
But you can implement it yourself - see [implementing transformer](https://github.com/apitte/negotiation/tree/master/.docs#implementing-transformer)

Negotiation annotations - I am not sure about these as I never used them yet.

**Comment by BigOHenry** [comment]
Thank you for quick reply :)

> I registered XmlTransformer. Same like at docs.
I have implemeted example XmlTransformer.

The problem is paramter in uri with `.xml`.
Example:
`http://localhost/api-rest/v1/lookup/lookup_title` - works fine, returns json
`http://localhost/api-rest/v1/lookup/lookup_title.xml` - this will call XmlTransformer, BUT parameter `lookup` has value `lookup_title.xml`

When there is a `integer` parameter in uri `/user/12.xml` this will throw error - "`Path request parameter \"id\" should be of type integer.`"

The great solution would be Accept header.

Thank you

**Comment by mabar** [comment]
> When there is a integer parameter in uri /user/12.xml this will throw error - "Path request parameter \"id\" should be of type integer."

Which version do you use? This was fixed in v0.5

> http://localhost/api-rest/v1/lookup/lookup_title.xml - this will call XmlTransformer, BUT parameter lookup has value lookup_title.xml

Not sure about that, maybe [pattern](https://github.com/apitte/core/blob/master/src/Schema/Endpoint.php#L329-L336) will need some changes

**Comment by BigOHenry** [comment]
using `"apitte/negotiation": "~0.5"`.

Problem is same at both cases `.xml` is part of the `path` parameter.

**Comment by mabar** [comment]
I am not sure, it works fine for us. Please try debug [generatePattern](https://github.com/apitte/core/blob/master/src/Schema/Endpoint.php#L311-L336) method

**Comment by BigOHenry** [comment]
Sorry i was wrong.
`http://localhost/api-rest/v1/lookup/lookup_title.xml` - parameter lookup has value `lookup_title.` So `xml` is gone but `dot` stayed.

```
"/api-rest/v1/lookup/(?P<lookup>[^/]+)" (37) // dump $rawPattern Endpoint.php:313
array (2) // dump $suffixes Endpoint.php:328
   0 => "json" (4)
   1 => "xml" (3)
"#/api-rest/v1/lookup/(?P<lookup>[^/]+)(json|xml)?$#U" (52) // dump return Endpoint.php:330

array (2) // dump $request->getParameters() at LookupController
   lookup => "lookup_title." (13)
   enabled-only => null
```
